jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      id: maven_package
      name: Package with Maven
      run: mvn package --file pom.xml
    - continue-on-error: true
      if: steps.maven_package.outcome == 'success'
      name: Stage JAR file artifact
      run: mkdir staging && cp uis/target/BiglyBT.jar staging/
    - continue-on-error: true
      if: steps.maven_package.outcome == 'success'
      name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: BiglyBT_${{ runner.os }}_JDK_${{ matrix.java-version }}
        path: staging
    strategy:
      matrix:
        java-version:
        - '8'
        - '11'
        - '17'
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
